import turtle
import time
#turtle.speed(0)
time.sleep(1)
turtle.pencolor("blue")
turtle.pensize(20)
turtle.goto(100,100)
turtle.pencolor("red")
time.sleep(2)
turtle.pencolor("black")
turtle.goto(100,-100)
time.sleep(1)
turtle.pensize(10)
turtle.goto(-100,-100)
turtle.pencolor("green")
time.sleep(2)
turtle.goto(-100,100)
turtle.pencolor("yellow")
time.sleep(1)
turtle.goto(0,0)